
export const USER_ROLE = {
    ADMIN: 1,
    STUDENT: 2,
    EDUCATOR: 3
}

export const MESSAGE = {
    DATABASE_ERROR: "DATABASE_ERROR",
    NO_DATA_FOUND: "NO_DATA_FOUND",
    SERVER_ERROR: "SERVER_ERROR",
    INCORRECT_EMAIL_OR_PASSWORD: "INCORRECT_EMAIL_OR_PASSWORD",
    USER_ALREADY_EXIST: "USER_ALREADY_EXIST",
    INVALID_DATA: "INVALID_DATA",
    UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
    INVALID_TOKEN: "INVALID_TOKEN",
    ACCESS_DENIED: "ACCESS_DENIED",
    BAD_DATA: "BAD_DATA"
}
